version: '3.4'

services:
  demoapi_docker_compose:
    image: ${DOCKER_REGISTRY-}demoapidockercompose
    build:
      context: .
      dockerfile: DemoAPI_Docker_Compose/Dockerfile
    depends_on:
        - sqldb
  sqldb:
      image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
      volumes:
        - sql-vol:/var/opt/mssql
      environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"

volumes:
  sql-vol: 